---
class: 4
flags: 0x0000
unid: 69A439B998D0766985258CF800648C3A
items:
  - name: $DesignerVersion
    type: text
    data: 8.5.3
  - name: $FileNames
    type: text
    data: ".classpath"
    signed: true
  - name: $Flags
    type: text
    data: ~C4g
  - name: $TITLE
    type: text
    data: ".classpath"
  - name: $FileData
    type: composite
    signed: true
    nonsummary: true
remaining: []