---
ACL:
  opaque: |
    Q0ECAO4CBQAAAAAABQC6ARAACgIqAgAAAAAoAAQAAAAEACgAjgEGADA5LzAxLzIwMjUgMDY6MjE6MjAg
    UE0gRGF2aWQgTGVlZHkvTm90ZXNJbjkgdXBkYXRlZCAtRGVmYXVsdC0AMDkvMDEvMjAyNSAwMjoxNjox
    MyBQTSBEYXZpZCBMZWVkeS9Ob3Rlc0luOSBhZGRlZCBPdGhlckRvbWFpblNlcnZlcnMAMDkvMDEvMjAy
    NSAwMjoxNjoxMyBQTSBEYXZpZCBMZWVkeS9Ob3Rlc0luOSBhZGRlZCBMb2NhbERvbWFpblNlcnZlcnMA
    MDkvMDEvMjAyNSAwMjoxNjoxMyBQTSBEYXZpZCBMZWVkeS9Ob3Rlc0luOSBhZGRlZCBFcGNvdC9Ob3Rl
    c0luOQAwOS8wMS8yMDI1IDAyOjE2OjEzIFBNIERhdmlkIExlZWR5L05vdGVzSW45IGFkZGVkIERhdmlk
    IExlZWR5L05vdGVzSW45ADA5LzAxLzIwMjUgMDI6MTY6MTMgUE0gRGF2aWQgTGVlZHkvTm90ZXNJbjkg
    dXBkYXRlZCAtRGVmYXVsdC0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMYCAAAAAAAASAIAAAAA
    dgIAAJ4CAAAAAAAAAAAAAEVBBgAAAAAAAAAAAAAAnAcJAC1EZWZhdWx0LQAAAEVBBgAAAAAAAAAAAAAA
    uAcZAENOPURhdmlkIExlZWR5L089Tm90ZXNJbjkAAABFQQYAAAAAAAAAAAAAAJqHEwBDTj1FcGNvdC9P
    PU5vdGVzSW45AAAARUEGAAAAAAAAAAAAAADaBxIATG9jYWxEb21haW5TZXJ2ZXJzAAAAAEVBAAAAAAAA
    AAAAAAAAQhASAE90aGVyRG9tYWluU2VydmVycwAA
DBOptions:
  - 0x00000200
  - 0x00480000
  - 0x00008000
  - 0x00000000
DBInfo:
  FTIndexPriority: 3
  FTOptions: 0x0044
  FTStopFile: ""
  FTThesaur: ""
  Flags: 0x0000
  MajorVersion: 1
  MinorVersion: 0
  Options: 0x0000
  Spare1: 0