---
class: 4
flags: 0x0000
unid: 86DC1E04D0AD146C85258CFA000663DB
items:
  - name: $DesignerVersion
    type: text
    data: 8.5.3
  - name: $FileNames
    type: text
    data: swagger/swagger-ui.css
    signed: true
  - name: $Flags
    type: text
    data: ~C4g
  - name: $FlagsExt
    type: text
    data: w
  - name: $MimeType
    type: text
    data: text/css
  - name: $TITLE
    type: text
    data: swagger/swagger-ui.css
  - name: $FileData
    type: composite
    signed: true
    nonsummary: true
remaining: []