---
class: 4
flags: 0x0000
unid: 0F658971D1DC983185258CFA00066398
items:
  - name: $DesignerVersion
    type: text
    data: 8.5.3
  - name: $FileNames
    type: text
    data: swagger/swagger-ui-bundle.js
    signed: true
  - name: $Flags
    type: text
    data: ~C4g
  - name: $FlagsExt
    type: text
    data: w
  - name: $TITLE
    type: text
    data: swagger/swagger-ui-bundle.js
  - name: $FileData
    type: composite
    signed: true
    nonsummary: true
remaining: []