---
class: 4
flags: 0x0000
unid: 96203DC4382C39E585258CFA000663B0
items:
  - name: $DesignerVersion
    type: text
    data: 8.5.3
  - name: $FileNames
    type: text
    data: swagger/swagger-ui-es-bundle-core.js
    signed: true
  - name: $Flags
    type: text
    data: ~C4g
  - name: $FlagsExt
    type: text
    data: w
  - name: $TITLE
    type: text
    data: swagger/swagger-ui-es-bundle-core.js
  - name: $FileData
    type: composite
    signed: true
    nonsummary: true
remaining: []