---
class: 4
flags: 0x0000
unid: 65B73677AD2BF30E85258CFA000663E0
items:
  - name: $DesignerVersion
    type: text
    data: 8.5.3
  - name: $FileNames
    type: text
    data: swagger/swagger-ui.js
    signed: true
  - name: $Flags
    type: text
    data: ~C4g
  - name: $FlagsExt
    type: text
    data: w
  - name: $TITLE
    type: text
    data: swagger/swagger-ui.js
  - name: $FileData
    type: composite
    signed: true
    nonsummary: true
remaining: []