---
class: 4
flags: 0x0000
unid: 4A02BAEE16F9229185258CF800648C3F
items:
  - name: $DesignerVersion
    type: text
    data: 8.5.3
  - name: $FileNames
    type: text
    data: ".settings/.jsdtscope"
    signed: true
  - name: $Flags
    type: text
    data: ~C4g
  - name: $TITLE
    type: text
    data: ".settings/.jsdtscope"
  - name: $FileData
    type: composite
    signed: true
    nonsummary: true
remaining: []